# Page settings
baseurl = "/"
title = "gotrades"
languageCode = "en-us"
theme = "hugo-elate-theme-master"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "gotradesdotnet@gmail.com"
  # Navigation
  [params.navigation]
    brand = "gotrades.net"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"
	loginregister = "LogIn/Register"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    # weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://gohugo.io"
      name = "LogIn/Register"
      weight = 10
  
  # Hero section
  [params.hero]
    title = "A Better Way to Trade Crypto Markets."
    subtitle = 'We have a system that works with predictive analytics, data, and market indicators powered by Hybrid Intelligence to support crypto market analysis. Instant News with filtered out noise,Facts,In depth Technical Analysis, Tips And Alerts.....
	<a href="http://vps161767.vps.ovh.ca/" target="_blank" title="LogIn/Register">Want to Know More</a>'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Technical Analysis"
    description = "A full technical analysis and background report on the coins we choose every month."
    url = "#"
    button = "Start Here"
    icon = "icon-chart"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "News"
    description = "Instant news updates.Stay on top of every headline that matters to your portfolio.."
    url = "#"
    button = "Know More"
    icon = "icon-book-open"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Alerts"
    description = "Trading setups, tips and alerts on coins and high potential ICO’s."
    url = "#"
    button = "Why us?"
    icon = "icon-feed"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/260981601"


  # Work section
  [params.work]
    enable = true
    title = "Invest Now in Blockchain economy"
    description = "With the unprecedented rise of cryptocurrencies and blockchain technology, new opportunities are arising in field of investment. As the traditional type of economy is reshaping its form, the money will flow into cryptocurrencies, either for the speculative purposes of gaining capital profit or by supporting projects that are built on decentralised platforms. Importantly, individual investors with little knowledge of cryptocurrency content do not want to miss opportunities to be exposed to undervalued digital assets. This is why we created gotrades.io where you can get all required information filtering out noise,Indepth analytics with the help of bleeding edge technologies,Crypto-Currency analysis by top hedge fund managers,Indetail Portfolio.. and many more in your finger tips"
    footertext = '** Past Results Can Not Gurantee Future Results <a href="http://plmd.me/" target="_blank">Know More</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Our services include Indepth market Analysis,Advanced technical Analysis,Curated content feeds from experts and Blockchain Trade Analytics so you can trade confidently and mitigate risks."

    [[params.services.item]]
      title = "Strategy"
      description = " The synergy of Man and Machine enables our Team and our customers to make smarter decisions.Our Trading Strategies  are Backtested and  Forward Tested"
      icon = "icon-graph"

    [[params.services.item]]
      title = "Collective Intelligence Platform"
      description = " We use advanced Big Data and AI analytics platform for cryptocurrencies.Our tech engine is continually learning by taking historical data and reviewing the performance of those predictions using the complex of statistical tools and machine-learning approaches "
      icon = "icon-layers2"
	  
    [[params.services.item]]
      title = "Blockchain Analyzer"
      description = "We monitor cold and hot wallets in order to analyze the potential sales in the market resulting from the transfers of large volumes of cryptocurrencies between wallets and exchanges."
      icon = "icon-organization"

      [[params.services.item]]
      title = "Beginner Friendly"
      description = "Whether you're a total beginner, an experienced , someone who wants to fully commit or just do it part time, we designed or resources section to suit and benefit all. You will acquire a competitive edge over others, learn how to reduce the risks and how to maximize your profits."      
      icon = "icon-graduation"
	  
  

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
  
	map = false
    enable = true
	form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        #["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        #["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@gotrades.net"],
        ["icon-globe", '<a href="https://gotrades.netlify.com//" target="_blank">gotrades.net</a>']
      ]
		

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"
	
	
 # loginregister section
  [params.loginregister]
    enable = false
    title = "this is login form"
    description = "To Login Click  Login or Register "

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
